name: Deploy to SAP BTP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build CAP project
        run: npx cds build

      #- name: Install MBT tool
      #  run: npm install -g mbt

      #- name: Build MTA archive
      #  run: mbt build -p cf

      - name: Install CF CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" -o cf-cli.tgz
          mkdir cf-cli
          tar -xvzf cf-cli.tgz -C cf-cli
          sudo mv cf-cli/cf /usr/local/bin/cf
          cf version


     # - name: Login to Cloud Foundry
     #   run: |
     #     cf api ${{ secrets.CF_API }}
     #     cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
     #     cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}

      - name: Deploy to BTP
        run: cf deploy mta_archives/*.mtar --no-confirm
