name: Deploy CoffeeX Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Check linting
        run: npx eslint . --ext .js,.cds
        continue-on-error: true

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm i -g mbt
          
      - name: Build CAP project
        run: npx cds build --profile production
        
      - name: Build MTA
        run: mbt build
        
      - name: Upload MTA artifact
        uses: actions/upload-artifact@v3
        with:
          name: mta-artifact
          path: mta_archives/*.mtar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: development
    steps:
      - uses: actions/checkout@v4
      
      - name: Download MTA artifact
        uses: actions/download-artifact@v3
        with:
          name: mta-artifact
          path: mta_archives
          
      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli
          
      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASS }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
        run: |
          cf api $CF_API
          cf login -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
          
      - name: Deploy to Cloud Foundry
        run: |
          cf deploy mta_archives/*.mtar --version-rule ALL -f
          
      - name: Verify deployment
        run: |
          cf apps
          cf services 